config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {omniauth_callbacks: "users/omniauth_callbacks"}
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root "groups#index"
  namespace :admin do 
    root "groups#index"
  end
  resources :users, only: [:show, :edit, :update, :destroy]

  resources :groups do
    resources :events, only: [:new, :create, :show, :edit, :update, :destroy]
      member do
      get :groupedit_members
      get :groupedit_photos
      get :groupedit_about
      get :groupshow_about
      get :groupshow_member
      get :groupshow_event
      get :groupshow_comment
      get :gropushow_photo
      post :join
      post :leave
    end
  end

  namespace :api, defaults: {format: :json} do
    namespace :v1 do
      resources :groups, except: [:new] do
        member do
          post :join
        end
      end
      resources :labels, except: [:new]
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
end

app/models/event.rb
class Event < ApplicationRecord
end

app/models/event_record.rb
class EventRecord < ApplicationRecord
end

app/models/group.rb
class Group < ApplicationRecord
  # validates_presence_of :name, :image, :description
  mount_uploader :image, GroupUploader
  has_many :label_groups
  has_many :labels, through: :label_groups
  has_many :group_records
  has_many :users, through: :group_records
  belongs_to :user
end

app/models/group_record.rb
class GroupRecord < ApplicationRecord
  belongs_to :group
  belongs_to :user
end

app/models/label.rb
class Label < ApplicationRecord
  has_many :label_groups, dependent: :restrict_with_error
  has_many :groups, through: :label_groups
end

app/models/label_group.rb
class LabelGroup < ApplicationRecord
  belongs_to :group
  belongs_to :label
end

app/models/role.rb
class Role < ApplicationRecord
  has_many :role_records
  has_many :users, through: :role_records
end

app/models/role_record.rb
class RoleRecord < ApplicationRecord
    belongs_to :user
    belongs_to :role
end

app/models/user.rb
class User < ApplicationRecord
  acts_as_token_authenticatable
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :omniauthable, omniauth_providers: [:facebook,:google_oauth2]
  # devise add name column must exist
  validates_presence_of :name
  has_many :group_records
  has_many :groups, through: :group_records
  
  def self.from_omniauth(auth, provider)
      puts "Facebook"
      puts provider == :facebook
      puts "google"
      puts provider == :google
      if provider == :facebook
        # Case 1: Find existing user by facebook uid
        user = User.find_by_fb_uid( auth.uid )
        if user
          user.fb_token = auth.credentials.token
          user.save!
          return user
        end

        # Case 2: Find existing user by email
        existing_user = User.find_by_email( auth.info.email )
        if existing_user
          existing_user.fb_uid = auth.uid
          existing_user.fb_token = auth.credentials.token
          existing_user.save!
          return existing_user
        end

        # Case 3: Create new password
        user = User.new
        user.fb_uid = auth.uid
        user.fb_token = auth.credentials.token
        user.email = auth.info.email
        user.password = Devise.friendly_token[0,20]
        user.name = auth.info.name
        user.save!
        return user
      elsif provider == :google
        # Case 1: Find existing user by facebook uid
        user = User.find_by_google_uid( auth.uid )
        if user
          puts "user find by uid"
          user.google_token = auth.credentials.token
          user.save!
          return user
        end

        # Case 2: Find existing user by email
        existing_user = User.find_by_email( auth.info.email )
        if existing_user
          puts "user find by email"
          existing_user.google_uid = auth.uid
          existing_user.google_token = auth.credentials.token
          existing_user.save!
          return existing_user
        end

        # Case 3: Create new password
        user = User.new
        user.google_uid = auth.uid
        user.google_token = auth.credentials.token
        user.email = auth.info.email
        user.password = Devise.friendly_token[0,20]
        user.name = auth.info.name
        user.save!
        puts "new user"
        return user
      end
  end

  has_many :role_records
  has_many :roles, through: :role_records
  has_and_belongs_to_many :labels

  mount_uploader :avatar, AvatarUploader

  def admin?
    self.roles.find_by(name: "admin")
  end
end

app/controllers/api_controller.rb
class ApiController < ActionController::Base
  # acts_as_token_authentication_handler_for User, fallback: :none
  before_action :authenticate_user!
  # skip_before_action :verify_authenticity_token # 整個 ApisController 關閉檢查
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :authenticate_user!
  def new
    @event = Event.new
  end
  def create
    @event = Event.new(event_params)
    if @event.save
      flash[:notice] = "Event was successfully created"
      rediedt_to group_event_path
    else
      flash.now[:alert] = "Event was failed to create"
      render :new
    end
  end

  private
  def event_params
    params.require(:event).permit(:name, :description, :image, :contacts, :address, :datetime, :location)
  end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :set_group, only: [:members, :gphotos, :show, :join, :leave]
  def index
    
  end
  def new
    @group = Group.new
    @labels = Label.all
  end
  def create
    @group = Group.new(group_params)
    if @group.save
      flash[:notice] = "Group was successfully created"
      redirect_to group_path
    else
      flash.now[:alert] = "Group was failed to create"
      render :new
    end
  end
  def groupedit_members

  end
  def groupedit_photos
    
  end
  def groupedit_about
    
  end
  def join
      group_record = @group.group_records.build()
      group_record.user = current_user
      if group_record.save!
        flash[:notice] = "You are successfully join the group '#{@group.name}'"
        redirect_back(fallback_location: root_path)
      end
  end
  def leave
    group_record = GroupRecord.where(group:@group,user:current_user)
    if group_record.size > 0
      if group_record.destroy_all
        flash[:notice] = "You left the group '#{@group.name}'"
        redirect_back(fallback_location: root_path)
      else
        flash[:alert] = "Error occurred when leaving group"
      end
    end
  end
  def show
    obj = GroupRecord.where(group:@group,user:current_user)
    if obj.size < 1
      @canJoin = true
    else
      @canJoin = false
    end
  end

  private
  def group_params
    params.require(:group).permit(:name, :image, :description)
  end
  def set_group
    @group = Group.find(params[:id])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update] 
  def show
    @user = User.find(params[:id])
    @labels = @user.labels.sort_by { |k| k["name"] }
  end
  def edit
    unless current_user.admin? or @user == current_user
      flash[:alert] = "Not allow!"
      redirect_to user_path(@user)
    end
  end
  def update
    @user.update(user_params)
    redirect_to user_path
  end
  def destroy
    delete_target_user = User.find(params[:id])
    delete_target_user_id = delete_target_user.id
    if current_user.admin? or current_user == delete_target_user
      if delete_target_user.destroy
        redirect_to admin_root_path, \
          notice: "User ID:" + delete_target_user_id.to_s + " has been deleted."
        # TODO: Display the error message if failed
      end
      # TODO: Handler the output of self-deleting
    else
      redirect_to root_path, alert: "Not allow!"
    end
  end

  private
  def set_user
    @user = User.find(params[:id])
  end
  def user_params
    params.require(:user).permit(:name, :avatar)
  end
end

app/helpers/api_helper.rb
module ApiHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/shared/_aboutgroup.html.erb
<div class="tab-pane" id="aboutgroup">
  <!-- right About Group -->
  <h1 class="page-header">Edit Group</h1>
  <!-- left column -->
  <div class="col-md-4 col-sm-6 col-xs-12">
    <div class="text-center">
      <img src="https://via.placeholder.com/400x200" class="avatar img-thumbnail" alt="avatar">
      <h6>Upload a different photo...</h6>
      <input type="file" class="text-center center-block well well-sm">
    </div>
  </div>
  <div class="col-md-8 col-sm-6 col-xs-12 personal-info">
      <form class="form-horizontal" role="form">
        <div class="form-group">
          <label class="col-lg-3 control-label">Group Name:</label>
          <div class="col-lg-8">
            <input class="form-control" value="" type="text">
          </div>
        </div>
        <div class="form-group">
          <label class="col-lg-3 control-label">Label:</label>
          <div class="col-lg-8">
            <input class="form-control" value="" type="text">
          </div>
        </div>
        <div class="form-group">
          <label class="col-lg-3 control-label">Description:</label>
          <div class="col-lg-8">
            <textarea class="form-control" id="exampleFormControlTextarea1" rows="3"></textarea>    
          </div>
        </div>
        <div class="form-group">
          <label class="col-md-3 control-label"></label>
          <div class="col-md-8">
            <input class="btn btn-primary" value="Save Changes" type="button">
            <span></span>
            <input class="btn btn-default" value="Cancel" type="reset">
          </div>
        </div>
      </form>
  </div>
</div>

app/views/shared/_carousel.html.erb
<header>
  <section>
    <div class="carousel fade-carousel slide" data-ride="carousel" data-interval="10000" id="bs-carousel">
      <!-- Indicators -->
      <ol class="carousel-indicators">
        <li data-target="#bs-carousel" data-slide-to="0" class="active"></li>
        <li data-target="#bs-carousel" data-slide-to="1"></li>
        <li data-target="#bs-carousel" data-slide-to="2"></li>
      </ol>
      <!-- Wrapper for slides -->
      <div class="carousel-inner">
        <div class="item slides active">
          <div class="overlay"></div>
          <div class="slide-1">
            <div class="hero">
              <hgroup>
                  <h1>Learn Keeper</h1>        
                  <h3>Get start your group and event</h3>
              </hgroup>
              <button class="btn btn-hero btn-lg" role="button" onclick="location.href='/groups/new'">Start a new group</button>
            </div>
          </div>
        </div>
        <div class="item slides">
          <div class="overlay"></div>
          <div class="slide-2"></div>
          <div class="hero">        
            <hgroup>
                <h1>Group Name</h1>        
                <h3> Event Name</h3>
            </hgroup>       
            <button class="btn btn-hero btn-lg" role="button" onclick="location.href='/groups/new'">>Start a new group</button>
          </div>
        </div>
        <div class="item slides">
          <div class="overlay"></div>
          <div class="slide-3"></div>
          <div class="hero">        
            <hgroup>
                <h1>Group Name</h1>        
                <h3>Event Name </h3>
            </hgroup>
            <button class="btn btn-hero btn-lg" role="button">Start a new group</button>
          </div>
        </div>
      </div> 
    </div>
  </section>
</header>

app/views/shared/_gphotos.html.erb
<!-- right Group Photos -->
 <div class="tab-pane" id="gphotos">
   <div class="table-responsive">
    <table class="table table-hover">
      <thead>
        <tr>
          <th>#</th>
          <th>Photo Name</th>
          <th>Description</th>
          <th>Photos count</th>
          <th>Date</th>
          <th>Edit</th>
          <th>Delete</th>
        </tr>
      </thead>
        <%# table cotents %>
    </table>
    <hr>
    <div class="row">
      <div class="col-md-4 col-md-offset-4 text-center">
        <ul class="pagination" id="myPager"></ul>
      </div>
    </div>
   </div><!--/table-resp-->            
 </div><!--/tab-pane join-->

app/views/shared/_landing_event.html.erb
<ul class="event-listing-container">
  <li class="row" type="none"><h4>WEDNESDAY, SEPTEMBER 12(依日期分類)</h4></li>
  <li class="row" type="none">
    <ul class="event-listing-row">
      <li class="row event-listing" type="none">時間幾點<em>個會去 going</em></li>
      <li class="row" type="none"><h4>group name</h4></li>
      <li class="row" type="none">event name</li>
    </ul>       
  </ul>

app/views/shared/_landing_group.html.erb
<div class="col-md-4 container">
  <h5>Group Name</h5>
  <%= image_tag("https://loremflickr.com/320/240/brazil,rio", alt: "", width:"100%", height:"225px", class: "card-img-top") %>
</div>

app/views/shared/_landing_pevent.html.erb
<div class="col-md-4"> 
  <div class="card mb-4 shadow-sm">
    <%= image_tag("https://loremflickr.com/320/240/brazil,rio", alt: "", width:"100%", height:"225px", class: "card-img-top") %>
    <div class="card-body">
      <h4 class="display-4">event datetime</h4>
      <h3 class="display-4">Group Name</h3>
      <p class="card-text">event adress</p>
      <p class="text-right"><small>postdate</small></p>
    </div>
  </div>
</div>

app/views/shared/_members.html.erb
<!-- right members -->
  <div class="tab-pane" id="members">
    <div class="table-responsive">
      <table class="table table-hover">
        <thead>
          <tr>
            <th>#</th>
            <th>Avatar</th>
            <th>Name</th>
            <th>Location</th>
            <th>Introduction count</th>
            <th>Message</th>
            <th>Delete</th>
          </tr>
        </thead>
          <%# table cotents %>
      </table>
      <hr>
      <div class="row">
        <div class="col-md-4 col-md-offset-4 text-center">
          <ul class="pagination" id="myPager"></ul>
        </div>
      </div>
     </div><!--/table-resp-->
  </div><!--/right group-->

app/views/shared/event_edit/_eventedit_about.html.erb
<div class="tab-pane" id="eabout">
  <!-- right About Group -->
  <h1 class="page-header">Edit Event</h1>
  <!-- left column -->
  <div class="col-md-4 col-sm-6 col-xs-12">
    <div class="text-center">
      <img src="https://via.placeholder.com/400x200" class="avatar img-thumbnail" alt="avatar">
      <h6>Upload a different photo...</h6>
      <input type="file" class="text-center center-block well well-sm">
    </div>
  </div>
  <div class="col-md-8 col-sm-6 col-xs-12 personal-info">
      <form class="form-horizontal" role="form">
        <div class="form-group">
          <label class="col-md-4 control-label">Event Name:</label>
          <div class="col-md-8">
            <input class="form-control" value="" type="text">
          </div>
        </div>
        <div class="form-group">
          <label class="col-md-4 control-label">Date:</label>
          <div class="col-md-8">
            <input class="form-control" value="" type="text">
          </div>
        </div>
        <div class="form-group">
          <label class="col-md-4 control-label">Location:</label>
          <div class="col-md-8">
            <select class="form-control">
              <option>Taipei</option>
              <option>Hsinchu</option>
              <option>Taichung</option>
              <option>Kaohsiung</option>
            </select>
          </div>
        </div>                 
        <div class="form-group">
          <label class="col-md-4 control-label">Address:</label>
          <div class="col-md-8">
            <input class="form-control" value="" type="text">
          </div>
        </div>
        <div class="form-group">
          <label class="col-md-4 control-label">Contacts:</label>
          <div class="col-md-8">
            <input class="form-control" value="" type="text">
          </div>
        </div>
        <div class="form-group">
          <label class="col-md-4 control-label">Description:</label>
          <div class="col-md-8">
            <textarea class="form-control" id="exampleFormControlTextarea1" rows="6"></textarea>    
          </div>
        </div>
        <div class="form-group">
          <label class="col-md-4 control-label"></label>
          <div class="col-md-8">
            <input class="btn btn-primary" value="Save Changes" type="button">
            <span></span>
            <input class="btn btn-default" value="Cancel" type="reset">
          </div>
        </div>
      </form>
  </div>
</div>

app/views/shared/event_edit/_eventedit_members.html.erb
<div class="tab-pane" id="emember">
  <div class="container">
    <div class="row">  
    <h4>Event Members</h4>
      <div class="table-responsive">
        <table id="mytable" class="table table-bordred table-striped">
         <thead>
           <th>Avatar</th>
           <th>Name</th>
           <th>Location</th>
           <th>Introduction</th>
           <th>Message</th>
           <th>Delete</th>
         </thead>
          <tbody>
            <tr>
              <td><%= image_tag("http://i.pravatar.cc/50",  height: "50px", width: "50px" ,alt: "Third slide", class: "d-block w-100") %></td>
              <td>User.name</td>
              <td>
                <select class="form-control-sm">
                  <option>Taipei</option>
                  <option>Hsinchu</option>
                  <option>Taichung</option>
                  <option>Kaohsiung</option>
                </select>
              </td>
              <td>CB 106/107 Street # 11 Wah Cantt Islamabad Pakistan</td>
              <td><p data-placement="top" data-toggle="tooltip" title="Edit"><button class="btn btn-primary btn-xs" data-title="Edit" data-toggle="modal" data-target="#edit" ><span class="glyphicon glyphicon-pencil"></span></button></p></td>
              <td><p data-placement="top" data-toggle="tooltip" title="Delete"><button class="btn btn-danger btn-xs" data-title="Delete" data-toggle="modal" data-target="#delete" ><span class="glyphicon glyphicon-trash"></span></button></p></td>
            </tr>
          </tbody>
        </table>
      </div>
    </div>
  </div>
</div>

app/views/shared/group_edit/_groupedit_about.html.erb
<div class="tab-pane" id="aboutgroup">
  <!-- right About Group -->
  <h1 class="page-header">Edit Group</h1>
  <!-- left column -->
  <div class="col-md-5">
    <div class="text-center">
      <img src="https://via.placeholder.com/400x200" class="avatar img-thumbnail" alt="avatar">
      <h6>Upload a different photo...</h6>
      <input type="file" class="text-center center-block well well-sm">
    </div>
  </div>
  <div class="col-md-7 personal-info">
      <form class="form-horizontal" role="form">
        <div class="form-group">
          <label class="col-lg-3 control-label">Group Name:</label>
          <div class="col-lg-8">
            <input class="form-control" value="" type="text">
          </div>
        </div>
        <div class="form-group">
          <label class="col-lg-3 control-label">Location:</label>
          <div class="col-lg-8">
            <select id="selectbasic" name="selectbasic" class="input-xlarge">
              <option>Taipei</option>
              <option>Hsinchu</option>
              <option>Kaohsiung</option>
            </select>           
          </div>
        </div>
        <div class="form-group">
          <label class="col-lg-3 control-label">Label:</label>
          <div class="col-lg-8">
            <select id="selectbasic" name="selectbasic" class="input-xlarge">
              <option>Art</option>
              <option>Computer</option>
              <option>Sports</option>
            </select>           
          </div>
        </div>
        <div class="form-group">
          <label class="col-lg-3 control-label">Description:</label>
          <div class="col-lg-8">
            <textarea class="form-control" id="exampleFormControlTextarea1" rows="3"></textarea>    
          </div>
        </div>
        <div class="form-group">
          <label class="col-md-3 control-label"></label>
          <div class="col-md-8">
            <input class="btn btn-primary" value="Save Changes" type="button">
            <span></span>
            <input class="btn btn-default" value="Cancel" type="reset">
          </div>
        </div>
      </form>
  </div>
</div>

app/views/shared/group_edit/_groupedit_members.html.erb
<!-- right members -->
  <div id="members">
    <table class="table table-striped custab">
      <thead>
        <tr>
          <th>#</th>
          <th>Avatar</th>
          <th>Name</th>
          <th>Location</th>
          <th>Role</th>
          <th>Message</th>
          <th>Delete</th>
        </tr>
      </thead>
        <tr>
         <td>1</td>
         <td>
          <%= image_tag("https://via.placeholder.com/50x50", width:"50px", height:"50px", style:"margin:0px") %>
         </td>
         <td>user.name</td> 
         <td>Taipei</td> 
         <td>user.role</td> 
         <td>
           <labe class="btn-bs-file btn btn-xs btn-primary">
             Message
           </labe>
         </td>
         <td>
           <labe class="btn-bs-file btn btn-xs btn-danger">
             Delete
           </labe>
         </td>       
        </tr>
    </table>
      <div class="row">
        <div class="col-md-4 col-md-offset-4 text-center">
          <ul class="pagination" id="myPager"></ul>
        </div>
      </div>
  </div><!--/right group-->      

app/views/shared/group_edit/_groupedit_photos.html.erb
<!-- right members -->
  <div id="members">
    <table class="table table-striped custab">
      <thead>
        <tr>
          <th>#</th>
          <th>Photo Name</th>
          <th>Description</th>
          <th>Photo count</th>
          <th>Date</th>
          <th>Edit</th>
          <th>Delete</th>
        </tr>
      </thead>
        <tr>
         <td>1</td>
         <td>photo.name</td> 
         <td>Lorem ipsum dolor sit amet.</td> 
         <td>photo.count</td> 
         <td>photo.datetime</td>
         <td>
           <labe class="btn-bs-file btn btn-xs btn-info">
             Edit
           </labe>
         </td>
         <td>
           <labe class="btn-bs-file btn btn-xs btn-danger">
             Delete
           </labe>
         </td>       
        </tr>
    </table>
      <div class="row">
        <div class="col-md-4 col-md-offset-4 text-center">
          <ul class="pagination" id="myPager"></ul>
        </div>
      </div>
  </div><!--/right group-->      

app/views/shared/group_show/_groupshow_about.html.erb
  <br>
  <h1>Hello,<%= current_user.name %>!</h1>
  <br>
  <%= image_tag(group.image.url.to_s,  height:"300",width: "100%" ,alt: "Third slide", class: "d-block w-100") %>
  <br>
    <div class="row">
      <h2>Group-Description</h2>
      <br>
      <p>
        <%= group.description %>
      </p>
      <%= canJoin.to_s %>
    </div>
  <br>
  <% if canJoin %>
    <%= link_to "Join us", join_group_path(@group), method: :post, class: "btn btn-primary btn-group" %>
  <% else %>
    <%= link_to "Leave Group", leave_group_path(@group), method: :post, class: "btn btn-primary btn-group" %>
  <% end %>
  <br>

app/views/shared/group_show/_groupshow_comment.html.erb
  <div class="card">
    <div class="card-body">
      <div class="row">
        <div class="col-md-2">
          <img src="http://i.pravatar.cc/100" class="img img-rounded img-fluid"/>
          <p class="text-secondary text-center">15 Minutes Ago</p>
        </div>
        <div class="col-md-10">
          <!-- contact user profile -->
          <p><a href=""><strong>Usre Name</strong></a></p>
         <div class="clearfix"></div>
          <p>Lorem Ipsum is simply dummy text of the pr make  but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.</p>
          <p>
            <a class="float-right btn btn-outline-primary ml-2"> <i class="fa fa-reply"></i> Reply</a>
            <a class="float-right btn text-white btn-danger"> <i class="fa fa-heart"></i> Like</a>
            <!-- 按reply才顯示 -->
            <%= render partial: "shared/group_show/groupshow_reply" %>
          </p>
        </div>
      </div>
      <div class="card card-inner">
        <div class="card-body">
          <div class="row">
            <div class="col-md-2">
                <img src="http://i.pravatar.cc/100" class="img img-rounded img-fluid"/>
                <p class="text-secondary text-center">15 Minutes Ago</p>
            </div>
            <div class="col-md-10">
              <!-- contact user profile -->
              <p><a href=""><strong>Usre Name</strong></a></p>
              <p>Lorem Ipsum is simply dummy text of the pr make  but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.</p>
              <p>
                <a class="float-right btn text-white btn-danger"> <i class="fa fa-heart"></i> Like</a>
               </p>
            </div><!-- col-md-10  -->
          </div><!-- row -->
        </div><!-- card-body -->
      </div>
    </div>
  </div>
    <!-- blank comment -->
  <div class="row">
    <h2>Comment...</h2>
  </div>
    <%= render partial: "shared/group_show/groupshow_reply" %>



  

app/views/shared/group_show/_groupshow_events.html.erb
<div class="row">
  <div class="col-md-4 item">
    <div class="thumbnail card">
      <div class="img-event">
        <%= image_tag("http://placeimg.com/640/360/any",  height:"200",width: "100%" ,alt: "Third slide", class: "d-block w-100") %>
      </div>
      <div class="caption card-body">
        <h4 class="group card-title inner list-group-item-heading">
              Event Name</h4>
          <p class="group inner list-group-item-text">
            <p class="lead">event.date</p>
            <h4>event.location</h4>
            event.contacts
            Lorem ipsum dolor sit amet, consectetur adipisicing elit. Tempore, corporis, voluptatum? Suscipit sapiente ut ipsum voluptates qui, voluptate quas iste!
          </p>
          <div class="row lge">
            <div class="btn-group">
              <button class="btn btn-info">Going</button>
              <button class="btn btn-danger">Not going</button>
            </div>
          </div>
      </div>
    </div>
  </div>
</div>

app/views/shared/group_show/_groupshow_member.html.erb
  <br>
<!-- user.avatar -->
  <div class="row">
  <% group_users.each do |user| %>
    <div class="col-md-3">
      <%= image_tag("http://i.pravatar.cc/100",  height: "200px", width: "200px" ,alt: "Third slide", class: "d-block w-100") %>
      <h4 class="text-center"><%= user.name %></h4> 
    </div>
  <% end %>
   
  </div>

app/views/shared/group_show/_groupshow_photos.html.erb
  <br>
<!-- photo alburm -->
  <div class="row">
    <div class="col-md-4">
      <%= image_tag("https://imgplaceholder.com/300x200/ff7f7f/333333/fa-image",  height: "200px", width: "200px" ,alt: "Third slide", class: "d-block w-100") %>
      <h4 class="text-center">photo alburm.name</h4>
      <p class="text-center">photo.alburm.date</p>
    </div>
    <div class="col-md-4">
      <%= image_tag("https://imgplaceholder.com/300x200/ff7f7f/333333/fa-image",  height: "200px", width: "200px" ,alt: "Third slide", class: "d-block w-100") %>
      <h4 class="text-center">photo alburm.name</h4>
      <p class="text-center">photo.alburm.date</p> 
    </div>
    <div class="col-md-4">
      <%= image_tag("https://imgplaceholder.com/300x200/ff7f7f/333333/fa-image",  height: "200px", width: "200px" ,alt: "Third slide", class: "d-block w-100") %>
      <h4 class="text-center">photo alburm.name</h4> 
      <p class="text-center">photo.alburm.date</p>
    </div>
  </div>
  <div class="row">
    <div class="col-md-4">
      <%= image_tag("https://imgplaceholder.com/300x200/ff7f7f/333333/fa-image",  height: "200px", width: "200px" ,alt: "Third slide", class: "d-block w-100") %>
      <h4 class="text-center">photo alburm.name</h4>
      <p class="text-center">photo.alburm.date</p> 
    </div>
    <div class="col-md-4">
      <%= image_tag("https://imgplaceholder.com/300x200/ff7f7f/333333/fa-image",  height: "200px", width: "200px" ,alt: "Third slide", class: "d-block w-100") %>
      <h4 class="text-center">photo alburm.name</h4> 
      <p class="text-center">photo.alburm.date</p>
    </div>
    <div class="col-md-4">
      <%= image_tag("https://imgplaceholder.com/300x200/ff7f7f/333333/fa-image",  height: "200px", width: "200px" ,alt: "Third slide", class: "d-block w-100") %>
      <h4 class="text-center">photo alburm.name</h4> 
      <p class="text-center">photo.alburm.date</p>
    </div>
  </div>

app/views/shared/group_show/_groupshow_reply.html.erb
<!-- 按reply才顯示 -->
 <div class="row">
  <div class="widget-area no-padding blank">
    <div class="status-upload">
      <form>
        <textarea placeholder="Say something......." ></textarea>
        <button type="submit" class="btn btn-success green"><i class="fa fa-share"></i>Send</button>
      </form>
    </div><!-- Status Upload  -->
  </div><!-- Widget Area -->
</div>