config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {omniauth_callbacks: "users/omniauth_callbacks"}
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root "groups#index"
  namespace :admin do 
    root "groups#index"
  end
  resources :users, only: [:show, :edit, :update, :destroy]

  resources :groups do
    resources :events, only: [:new, :create, :show, :edit, :update, :destroy]
      member do
      get :groupedit_members
      get :groupedit_photos
      get :groupedit_about
      get :groupshow_about
      get :groupshow_member
      get :groupshow_event
      get :groupshow_comment
      get :gropushow_photo
      post :join
      post :leave
    end
  end

  namespace :api, defaults: {format: :json} do
    namespace :v1 do
      resources :groups, except: [:new] do
        member do
          post :join
        end
      end
      resources :labels, except: [:new]
    end
  end
end

app/models/group.rb
class Group < ApplicationRecord
  # validates_presence_of :name, :image, :description
  mount_uploader :image, GroupUploader
  has_many :label_groups
  has_many :labels, through: :label_groups
  has_many :group_records
  has_many :users, through: :group_records
  belongs_to :user
end

app/controllers/admin/groups_controller.rb
class Admin::GroupsController < ApplicationController
  before_action :authenticate_admin
  def index
    @user = User.all
    @groups = Group.all
    @events = Event.all
  end
end

app/controllers/api/v1/groups_controller.rb
class Api::V1::GroupsController < ApiController
  def index
    @groups = Group.all
  end
  def show
    @groups = Group.all
  end
  def create
    # create new group
    @group = Group.new()
    group_params
    @group.name = params[:name]
    @group.image = params[:image]
    @group.location = params[:location]
    @group.description = params[:description]
    @group.user = current_user
    groupLabels = JSON.parse(params[:selectedLabels])
    @group_labels = Array.new
    # save new group
    if @group.save! #create group labels if group created successfully
      # add current user to group_records
      group_record = @group.group_records.build()
      group_record.user = current_user
      group_record.save!
      # add selected labels to label_groups
      groupLabels.each do |label|
        obj = Label.find(label["id"])
        if obj
          group_label = @group.label_groups.build()
          group_label.label = obj
          group_label.save!
          @group_labels.push(group_label)
        end
      end
      render json:{
        group:@group.as_json(except:[:created_at,:updated_at]),
        group_labels:@group_labels.as_json(except:[:created_at,:updated_at]),
        message:"OK"
      }
    else
      render json:{
        errors: @group.errors
      }
    end

  end

  private

  def group_params
    params.permit(:name,:image,:description,:location,:selectedLabels)
  end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :set_group, only: [:members, :gphotos, :show, :join, :leave]
  def index
    
  end
  def new
    @group = Group.new
    @labels = Label.all
  end
  def create
    @group = Group.new(group_params)
    if @group.save
      flash[:notice] = "Group was successfully created"
      redirect_to group_path
    else
      flash.now[:alert] = "Group was failed to create"
      render :new
    end
  end
  def groupedit_members

  end
  def groupedit_photos
    
  end
  def groupedit_about
    
  end
  def join
      group_record = @group.group_records.build()
      group_record.user = current_user
      if group_record.save!
        flash[:notice] = "You are successfully join the group '#{@group.name}'"
        redirect_back(fallback_location: root_path)
      end
  end
  def leave
    group_record = GroupRecord.where(group:@group,user:current_user)
    if group_record.size > 0
      if group_record.destroy_all
        flash[:notice] = "You left the group '#{@group.name}'"
        redirect_back(fallback_location: root_path)
      else
        flash[:alert] = "Error occurred when leaving group"
      end
    end
  end
  def show
    obj = GroupRecord.where(group:@group,user:current_user)
    if obj.size < 1
      @canJoin = true
    else
      @canJoin = false
    end
  end

  private
  def group_params
    params.require(:group).permit(:name, :image, :description)
  end
  def set_group
    @group = Group.find(params[:id])
  end
end

app/helpers/admin/groups_helper.rb
module Admin::GroupsHelper
end

app/helpers/api/v1/groups_helper.rb
module Api::V1::GroupsHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/views/shared/admin/group/_admin_event.html.erb
<div class="col-md-12">
    <table class="table table-striped custab text-center">
    <thead>
        <tr >
            <th class="text-center">Event ID</th>
            <th class="text-center">Event Name</th>
            <th class="text-center">Attendee Count</th>
            <th class="text-center">Update</th>
            <th class="text-center">Delete</th>

        </tr>
    </thead>
        <% @events.each do |event| %>
            <tr>
                <td><%= event.id %></td>
                <td><%= event.name %></td>
                <td><%= event.attendees_count %></td>
                <td class="text-center">
                    <%= button_to(edit_group_event_path(event.group_id, event), class:"btn btn-info btn-xs", :method => :get) do %>
                        <span class="glyphicon glyphicon-edit">Update</span>
                    <% end %>
                </td>
                <td class="text-center">
                    <%= button_to(group_event_path(event.group_id, event), class:"btn btn-danger btn-xs", :method => :delete, data: { confirm: "You sure?" }) do %>
                        <span class="glyphicon glyphicon-remove">Delete</span>
                    <% end %>
                </td>
            </tr>
        <% end %>
    </table>
</div>

app/views/shared/admin/group/_admin_group.html.erb
<div class="col-md-12">
    <table class="table table-striped custab text-center">
    <thead>
        <tr >
            <th class="text-center">Group ID</th>
            <th class="text-center">Group Name</th>
            <th class="text-center">Location</th>
            <th class="text-center">Labels</th>
            <th class="text-center">Update</th>
            <th class="text-center">Delete</th>

        </tr>
    </thead>
        <% @groups.each do |group| %>
            <tr>
                <td><%= group.id %></td>
                <td><%= group.name %></td>
                <td><%= group.location %></td>
                <td>
                    <select name="" id="" style="width: 70px">
                        <% group.labels.each do |label| %>
                            <option><%= label.name %></option>
                        <% end %>
                    </select>
                </td>
                <td class="text-center">
                    <%= button_to(edit_group_path(group), class:"btn btn-info btn-xs", :method => :get) do %>
                        <span class="glyphicon glyphicon-edit">Update</span>
                    <% end %>
                </td>
                <td class="text-center">
                    <%= button_to(group_path(group), class:"btn btn-danger btn-xs", :method => :delete, data: { confirm: "You sure?" }) do %>
                        <span class="glyphicon glyphicon-remove">Delete</span>
                    <% end %>
                </td>
            </tr>
        <% end %>
    </table>
</div>

app/views/shared/admin/group/_admin_user.html.erb
<div class="col-md-12">
    <table class="table table-striped custab text-center">
    <thead>
        <tr >
            <th class="text-center">ID</th>
            <th class="text-center">Avatar</th>
            <th class="text-center">Name</th>
            <th class="text-center">Email</th>
            <th class="text-center">Location</th>
            <th class="text-center">Role</th>
            <th class="text-center">Update</th>
            <th class="text-center">Delete</th>

        </tr>
    </thead>
            <% @user.each do |u| %>
                <tr>
                    <td><%= u.id %></td>
                    <td class="text-center">
                    <%= link_to user_path(u.id) do %>
                        <% if u.avatar.url.present? %>
                            <%= image_tag(u.avatar.url, height: "50px", width: "50px")%>
                        <% else %>
                            <%= image_tag("https://via.placeholder.com/50x50", height: "50px", width: "50px") %>
                        <% end %>
                    <% end %>
                    </td>
                    <td><%= u.name %></td>
                    <td><%= u.email %></td>
                    <td><%= u.location %></td>
                    <td>
                        <select name="" id="" style="width: 70px">
                            <% u.roles.each do |r| %>
                                <option><%= r.name %></option>
                            <% end %>
                        </select>
                    </td>
                    <td class="text-center">
                        <%= button_to(edit_user_path(u), class:'btn btn-info btn-xs', :method => :get) do %>
                            <span class="glyphicon glyphicon-edit">Update</span>
                        <% end %>
                    </td>
                    <td class="text-center">
                        <%= button_to(user_path(u), class:'btn btn-danger btn-xs', :method => :delete, data: { confirm: "You sure?" }) do %>
                            <span class="glyphicon glyphicon-remove">Delete</span>
                        <% end %>
                    </td>
                </tr>
            <% end %>
    </table>
</div>